[package]
name = "bvp_token"
version = "0.1.0"
edition = "2021"

[lib]
name = "bvp_token"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
solana-program = "1.18.6"
