[workspace]
members = ["programs/bvp_token"]

[programs.devnet]
bvp_token = "DGsg8rU5S9EQMYZaZgxJ2zihAX39jSd6ESnfZ5MQePQk"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "mocha -r ts-node/register tests/**/*.ts"
