[programs.devnet]
bvp_token = "3FpX6Erkk2E8bdwrcpE76pR1LsoHuoSPappittGvqfEA"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
